name: notsky
description: "Another bluesky client, made with Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  flutter_lints: ^5.0.0
  atproto_core: ^0.11.2
  bluesky: ^0.18.9
  shared_preferences: ^2.5.2
  atproto: ^0.13.3
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/login_background.jpg
